### ISSUE TITLE
关于训练中遇到的几个问题，希望得到建议

### ISSUE THREAD

**Issue by 741077510** [xhzdeng/crpn#11]
论文中提到，将ICDAR2015将短边resize到900，ICDAR2013将短边resize到640，这是靠反复实验得到的一个参数吗？或者说有没有什么选择的方法？作者有没有考虑过multi-scale的测试？我换了数据，loss在训练一千次之后，一直到十万次，数值一直是在零点几到二点几之间波动，learning rate已经设置到1*e-5，感觉一直没有收敛，请问作者在之前实验过程中遇到过吗？

**Comment by xhzdeng** [comment]
hi, @741077510 
1. 论文中的参数是在数据集上实验得到的折中结果。
2. 没有试过multi-scale测试，我们希望在效率上也有竞争力。
3. 模型在ICDAR上经过两万次迭代后性能就无明显变化了，所以并未遇到过这个问题。

**Comment by PeiChenPing** [comment]
@741077510  hello,i think you have already trained your dataset,can you tell me how to make the dataset format?

**Comment by 741077510** [comment]
@PeiChenPing you can see the closed issues where i have given the fomat of my datasets
