### ISSUE TITLE
finetune 了20000步以后结果只有78%

### ISSUE THREAD

**Issue by Haiyan-Chris-Wang** [xhzdeng/crpn#19]
您好，我按照您论文中说的，在synth text pretrain的model基础上，在icdar13 和icdar15的training dataset上training了20000步，lr是0.0001, 但是结果只有78%， 麻烦问一下这是什么问题呢？是什么参数没设对吗？@xhzdeng

**Comment by xhzdeng** [comment]
抱歉这么迟回复，我个人猜测有两方面的可能：第一是我在训练时是过滤掉了仅包含单个字符的样本；第二测试时图像分辨率对检测性能的影响较大，建议尝试一下不同的分辨率。^_^.

**Comment by Haiyan-Chris-Wang** [comment]
@xhzdeng 感谢您的解答！尝试了在test的时候把短边resize到不同尺度，900还是最好的一个，其它尺度的结果能到了75， 76的样子，你当时也是用的900吧？ 还有就是training的问题，这个78%的结果是我在synth text pretrain的model基础上，在icdar13 和icdar15的training dataset上，先用0.001的lr train了40000步，然后用0.0001的lr train了30000步得到的结果。如果直接用0.0001的lr train的话，效果很不好，麻烦问一下，您当时就直接在synth text pretrain的model基础上用0.0001 train20000步就可以得到84%的结果了吗？（有可能是我没有过滤掉仅包含单个字符的样本）

**Comment by xhzdeng** [comment]
@whyccny 是的，我是直接在synth模型上用1e-4迭代20000次得到的84%。建议也可以降低学习率继续训练，但我训练时性能没有明显变化。

**Comment by Haiyan-Chris-Wang** [comment]
@xhzdeng 会不会是您上传的synth模型不一样，这个synth text pretrain的model我测试了一下结果只有58%，然后如果按照您说的在这个上边用1e-4迭代20000次的结果只有65% 。 (而且我注意了一下结果，recall的结果很高，有81%， 但precision的结果很低导致最终结果不好，但是我测试的时候的pt_thres确实是0.5)  您当时的synth text pretrain的model有没有测试结果？大概有多少呢？

**Comment by Haiyan-Chris-Wang** [comment]
@xhzdeng 感觉不应该差这么多呀

**Comment by xhzdeng** [comment]
@whyccny Caffe这个版本我很久没用了，我没记错的话预训练模型好像也是58%左右。我刚在PyTorch版本上试了一下，迭代20000次后也是在84%左右哈。 ^_^.

**Comment by Haiyan-Chris-Wang** [comment]
@xhzdeng 哇！有pytorch版本吗？是现在还没有release吗？方不方便分享一下？

**Comment by Haiyan-Chris-Wang** [comment]
@xhzdeng 这个会因为版本的问题吗？理论上caffe的操作不会影响结果吧

**Comment by xhzdeng** [comment]
@whyccny 二者检测性能上是一样的哈。我争取快点release，现在还没有review过代码。^_^.

**Comment by xhzdeng** [comment]
@whyccny 如果其他参数你都没有修改过的话，现在唯一剩下的可能性就是数据问题了。

**Comment by Haiyan-Chris-Wang** [comment]
@xhzdeng 多谢多谢，非常期待你的pytorch版本！^_^.  不过数据这个，难道是我转化成的voc格式有问题吗，而且后来我也把单个的字符都过滤掉了啊。这个icdar13和15的数据总共也不大，能不能麻烦您上传一份当时train网络的voc格式的数据啊？

**Comment by xhzdeng** [comment]
> <annotation>
	<folder>ICDAR</folder>
	<filename>000001.jpg</filename>
	<source>
		<database>ICDAR</database>
		<annotation>PASCAL VOC</annotation>
		<image>100.jpg</image>
		<flickrid>NULL</flickrid>
	</source>
	<owner>
		<flickrid>NULL</flickrid>
		<name>NULL</name>
	</owner>
	<size>
		<width>640</width>
		<height>480</height>
		<depth>3</depth>
	</size>
	<segmented>0</segmented>
	<object>
		<name>text</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<x1>158</x1>
			<y1>128</y1>
			<x2>158</x2>
			<y2>181</y2>
			<x3>411</x3>
			<y3>181</y3>
			<x4>411</x4>
			<y4>128</y4>
		</bndbox>
	</object>
	<object>
		<name>text</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<x1>443</x1>
			<y1>128</y1>
			<x2>443</x2>
			<y2>169</y2>
			<x3>501</x3>
			<y3>169</y3>
			<x4>501</x4>
			<y4>128</y4>
		</bndbox>
	</object>
	<object>
		<name>text</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<x1>64</x1>
			<y1>200</y1>
			<x2>64</x2>
			<y2>243</y2>
			<x3>363</x3>
			<y3>243</y3>
			<x4>363</x4>
			<y4>200</y4>
		</bndbox>
	</object>
	<object>
		<name>text</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<x1>394</x1>
			<y1>199</y1>
			<x2>394</x2>
			<y2>239</y2>
			<x3>487</x3>
			<y3>239</y3>
			<x4>487</x4>
			<y4>199</y4>
		</bndbox>
	</object>
	<object>
		<name>text</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<x1>72</x1>
			<y1>271</y1>
			<x2>72</x2>
			<y2>312</y2>
			<x3>382</x3>
			<y3>312</y3>
			<x4>382</x4>
			<y4>271</y4>
		</bndbox>
	</object>
</annotation>

**Comment by Haiyan-Chris-Wang** [comment]
@xhzdeng 
所以我需要提前resize这个dataset吗？ 我看到你的代码里不是会把图片随机的resize到480 512  544  576 608 640 672 704 736 768 800这些尺度吗？  
这是我的dataset：
![screenshot from 2018-08-30 22-38-52](https://user-images.githubusercontent.com/31809601/44889830-adc8cf00-aca5-11e8-894d-60dd9f945ebf.png)

**Comment by xhzdeng** [comment]
@whyccny 这是ICDAR 2013训练集的第一张图像，我直接从原始标注复制过来的，无需提前resize哈。

**Comment by Haiyan-Chris-Wang** [comment]
@xhzdeng 嗷嗷，那我们这个数据应该也是一样的，这就很奇怪了。。。您train的时候有没有什么tricks，比如用0.01先trian 100 步之类的？还有就是想问一下您的pytorch代码大概什么时候release呢？ 真的是非常期待想要复现一下这个论文的结果^_^

**Comment by xhzdeng** [comment]
@whyccny 没有trick哈，所有代码都贴上来了。你试试不用13的数据训练呢？我13的数据是重新标注过的。

**Comment by xhzdeng** [comment]
@whyccny 单用15的数据在15上测试效果也是差不多的。

**Comment by Haiyan-Chris-Wang** [comment]
@xhzdeng 好吧，那我有空再试试，不过还是期待您的pytorch，希望早点放出来让我们膜拜一下！

**Comment by Haiyan-Chris-Wang** [comment]
@xhzdeng 抱歉再打扰一下，我突然发现您的数据集坐标是逆时针的？所以您的13/15 的training数据集的四个坐标顺序都是左上，左下，右下，右上吗？

**Comment by xhzdeng** [comment]
@whyccny 是的，但标注顺序没影响，我输入的时候会再排序。

**Comment by d0ng1ee** [comment]
求大佬的pytorch版本啊！！！ @xhzdeng
