### ISSUE TITLE
关于ICDAR2013和ICDAR2015格式问题

### ISSUE THREAD

**Issue by lw19951231** [xhzdeng/crpn#3]
谢谢分享论文和代码，新人小白想问问关于ICDAR2013和ICDAR2015数据库数据局格式处理的代码是否会发布，谢谢。

**Comment by xhzdeng** [comment]
Hi, @lw19951231. 网上有很多将ICDAR的txt转换为VOC格式的xml文件的代码，很容易就能找到。我自己的代码比较复杂，可能用起来不是很方便，所以没有打算发布。^_^
