### ISSUE TITLE
将自己的数据集做成的VOC格式不知道是否存在问题？

### ISSUE THREAD

**Issue by 741077510** [xhzdeng/crpn#6]
查看了作者读取数据集的函数，发现读取的是四个点八个坐标值，与网上的教程“将ICDAR21015转化为VOC2007”有所区别，那里提及的bndbox是以x,y,w,h,angle的格式制作annotations。我参照作者的代码，将数据集制作为如下格式，不知道与作者用于训练的VOC2007数据集的格式是否有差异？
![image](https://user-images.githubusercontent.com/13686669/38909902-42f1bedc-42f9-11e8-838c-56d5c1445da5.png)

**Comment by xhzdeng** [comment]
没有问题。^_^

**Comment by 741077510** [comment]
谢谢，已经成功训练了模型，运行了demo.py得到了可视化的结果，但是识别效果并不好，learning rate分别设置为 1e-3，1e-5进行了训练，,训练数据1w张图片,迭代次数60000，两次的结果每张测试图的框的召回率都挺低，很多框都找不到，请问有什么调参的建议吗？
