### ISSUE TITLE
the third step in searching and grouping corners candidates

### ISSUE THREAD

**Issue by SchumannTian** [xhzdeng/crpn#7]
i am confused with the sentences below
"For each diagonal, select any one corner from last two types and rotate the diagonal until three points (two endpoints and the third one) are collinear, then a quadrilateral proposal determined by those two diagonals will be obtained."
how could three conners determine a quadrilateral proposal? while rotating the diagonal, where is the fixed point?

**Comment by xhzdeng** [comment]
Hi, @SchumannTian. The fixed point is the center of the diagonal. We suppose the fixed point is a quadrangle's center and rotating the diagonal around this point will obtain another diagonal. The third point just indicates when to stop rotating. ^_^.

**Comment by SchumannTian** [comment]
@xhzdeng thanks for the response! so does that mean the proposals are supposed to be parallelograms instead of quadrangles like trapezoids?

**Comment by xhzdeng** [comment]
@SchumannTian. That is what I thought. ^_^.
